---
title: "Syllabus"
---

```{r}
#| label: package-loads
#| include: false
#| message: false
library(kableExtra)
```

# DS 201 Introduction to Data Science


# Instructor Information

* **Instructor:** Dr. Jason M. Graham

* **Office:** LSC 319A 
    + **Office Hours:** TBD You may also make an appointment to meet with us outside of scheduled office hours. Appointments are not necessary for regularly scheduled office hours.

* **Email:** <jason.graham@scranton.edu>

* **Phone:** (570) 941-7491

* **Course Page:** [link](https://intro-ds.netlify.app/)

# Course Materials

## Required Readings

* Hands-On Programming with R by Garrett Grolemund, freely available online [here](https://rstudio-education.github.io/hopr/).

* R for Data Science by Hadley Wickham & Garrett Grolemund, freely available online [here](https://r4ds.had.co.nz/index.html).

* Data Science: A First Introduction by Tiffany Timbers, Trevor Campbell, and Melissa Lee, freely available online [here](https://datasciencebook.ca/).

* Telling Stories with Data by Rohan Alexander, freely available online [here](https://tellingstorieswithdata.com/).



## Recommended Readings 

* Statistical Inference via Data Science A ModernDive into R and the Tidyverse by Chester Ismay & Albert Y. Kim, freely available online [here](https://moderndive.com/).

* An Introduction to Statistical Learning 2nd Ed. by James, Witten, Hastie, and Tibshirani, freely available online [here](https://www.statlearning.com/).

* Tree-Based Methods for Statistical Learning by Brandon M. Greenwell, freely available online [here](https://bgreenwell.github.io/treebook/).

* Advanced R by Wickham, freely available online [here](https://adv-r.hadley.nz/).

* R Packages by Wickham, freely available online [here](https://r-pkgs.org/).
